### PR TITLE
Fix build with Musl libc

### PR DESCRIPTION
**Pull request by PureTryOut**
RTLD_DEEPBIND is glibc specific and not in POSIX, guard it's use

TEMP_FAILURE_RETRY is glibc specific. If it's not available, define it.
The implementation is taken from Bionic which is permissively licensed,
so should be compatible with the licensing here but IANAL

On 32-bit arches input_event->time is undefined when using a time64
kernel. Instead read the input_event_sec and input_event_usec values
directly and save those instead.
Also make sure to support input_event_sec and input_event_usec on
non-time64 kernels (downstream Android ones for example)

This is a recreation of https://git.sailfishos.org/mer-core/mce/merge_requests/148 since sadly you guys moved away from the FOSS Gitlab. There were some comments on the original MR which I'll apply, but for now I'm just recreating everything I had open.

### CODE REVIEW

**Comment by spiiroin** [comment]
> There were some comments on the original MR which I'll apply

@PureTryOut Do you still plan to make those changes?

As the requested changes were rather minor: if you are busy with other things atm, we could also make it so that I'll merge this as-is and make those changes myself.

**Review by spiiroin — APPROVED** [review]

**Comment by spiiroin** [comment]
> would be nice if you could make those minor changes

Done. Tagged as mce 1.108.0

@PureTryOut  If/when you have time, please check that musl build still works.

**Comment by PureTryOut** [comment]
Just did, it's closer but it seems some imports are wrong now?

```
In file included from modules/../mce.h:31,
                 from modules/radiostates.c:27:
modules/../datapipe.h:28:11: fatal error: glib.h: No such file or directory
   28 | # include <glib.h>
      |           ^~~~~~~~
compilation terminated.
make: *** [Makefile:385: modules/radiostates.pic.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from modules/filter-brightness-als.c:36:
modules/../mce-io.h:33:10: fatal error: glib.h: No such file or directory
   33 | #include <glib.h>
      |          ^~~~~~~~
compilation terminated.
```

`glib.h` _is_ available at `/usr/include/glib-2.0/glib.h`.

**Comment by Thaodan** [comment]
Can you check if that path is used by the compiler in this file? It should be there.
https://github.com/sailfishos/mce/blob/master/Makefile#L293

**Comment by spiiroin** [comment]
> Just did, it's closer but it seems some imports are wrong now?

Weird. There ought to have been no changes to package deps / how they are handled...

What 'make' flavor / version you are using and how it ends up executed?

For example, what I see during manual radiostates plugin build is:

    PlatformSDK mce % sb2 make modules/radiostates.so
    cc -c -o modules/radiostates.pic.o modules/radiostates.c ... -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/usb-moded -I//usr/include/dbus-1.0 -I//usr/lib/dbus-1.0/include
    cc -shared -o modules/radiostates.so modules/radiostates.pic.o -g -Wl,--as-needed -L//usr/lib -lgobject-2.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lglib-2.0 -ldbus-1 -ludev

> It should be there.
> https://github.com/sailfishos/mce/blob/master/Makefile#L293

In case of module/plugin, the relevant part is a bit later: https://github.com/sailfishos/mce/blob/master/Makefile#L376

**Comment by PureTryOut** [comment]
> What 'make' flavor / version you are using and how it ends up executed?

Just GNU make. Executed as just `make` in the root of the source tree.

**Comment by spiiroin** [comment]
> Just GNU make. Executed as just `make` in the root of the source tree.

You are not cross-compiling? So that what is at /usr/include/glib-2.0/glib.h is what actually is and should be used for mce compilation? No errors on make exec?

If I attempt to use just "make" (normal host compile) instead of "sb2 make" (cross compile for target arch), I get

- a bunch of pkg-config related errors about missing pc files
- practically the same missing glib.h error as you had above

Which is because: while glib dev package happens to be installed on the host too, some of the other dev packages are not ->  "pkg-config --cflags gobject-2.0 glib-2.0 gmodule-2.0 dbus-1 usb_moded  libudev" emits diagnostics to stderr, but does not write -I flags even for those packages that are present to stdout -> make gets empty set of options to add.

Maybe your build env is missing some devel packages that mce build needs? (rpm build would checks those, but plain make does not and fails in less than graceful manner)

**Comment by PureTryOut** [comment]
> You are not cross-compiling? So that what is at /usr/include/glib-2.0/glib.h is what actually is and should be used for mce compilation? No errors on make exec?

Yes, yes and yes.

> Maybe your build env is missing some devel packages that mce build needs?

Seems like it is yes, I added usb-moded and suddenly it compiled :tada: 

So I can confirm with this PR it now works fine, thanks!

**Pull request merged**
